# Generated by Django 2.0.4 on 2018-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Uploaded image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
