# Generated by Django 2.0.4 on 2018-04-23 11:05

from django.db import migrations, models
import upload_image.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload_image.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image')),
                ('title', models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image')),
                ('description', models.TextField(default='', verbose_name='Description of the uploaded image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
